DocsExchange/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using AutoMapper;
using BusinessLogic.Interfaces;
using DataAccess;
using DataAccess.Context;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using WebStore.Models;
using WebStore.Models.Filters;
using WebStore.ViewModels;
using Newtonsoft.Json;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IProductBusinessLogic _productBusinessLogic;
        private readonly IProductImagesBusinessLogic _productImagesBusinessLogic;
        private readonly WebStoreDbContext _context;
        private readonly IMapper _mapper;

        public CatalogController(IProductBusinessLogic productBusinessLogic, 
                                IProductImagesBusinessLogic productImagesBusinessLogic,
                                IMapper mapper, WebStoreDbContext context)
        {
            _mapper = mapper;
            _context = context;
            _productBusinessLogic = productBusinessLogic;
            _productImagesBusinessLogic = productImagesBusinessLogic;
        }

        [HttpGet]
        public string getGoods()
        {
            return JsonConvert.SerializeObject(_productBusinessLogic.GetAllActive().Select(_mapper.Map<ProductView>).ToList());
        }
        // GET
        public IActionResult Index()
        {
            //var _colorRep = new ProductColorRepository(_context);
            //var _metalRep = new ProductMetalRepository(_context);
            //var _typeRep = new ProductTypeRepository(_context);
            //var _statusRep = new ProductStatusRepository(_context);
            //var _statusAvRep = new ProductAvStatusRepository(_context);
            //var _genderRep = new GenderRepository(_context);

            try
            {
                //var filters = new ProductsFilters()
                //{
                //    ColorList = _colorRep.GetAllAvailable().Select(_mapper.Map<ProductColorView>),
                //    MetalList = _metalRep.GetAllAvailable(),
                //    GenderList = _genderRep.GetAllAvailable(),
                //    TypeList = _typeRep.GetAllAvailable(),
                //    StatusList = _statusRep.GetAllAvailable(),
                //    StatusAvList = _statusAvRep.GetAllAvailable()
                //};

                //ViewBag.Data = JsonConvert.SerializeObject(_productBusinessLogic.GetAllActive().Select(_mapper.Map<ProductView>).ToList());
                //ViewBag.Filters = filters;
                
                return View();
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Filter(ProductsFilters filtersEvents)
        {
            var prodFilter = filtersEvents.Name;
            var products = _productBusinessLogic
                .GetAll()
                .Where(@prod =>
                    FilterByName(@prod, prodFilter))
                .ToList();
            List<ProductView> models = new List<ProductView>();
            foreach (var item in products)
            {
                models.Add(_mapper.Map<ProductView>(item));
            }
            ViewBag.Data = models.OrderBy(x => x.Name).ToList();
            return View(nameof(Index));
        }
        private bool FilterByName(Product @event, string prodFilter)
        {
            if (String.IsNullOrEmpty(prodFilter))
                return true;
            if (@event.Name == null)
                return false;
            var dep = _productBusinessLogic.GetByStr(@event.Name).FirstOrDefault();
            if (dep != null && dep.Name.Contains(prodFilter))
                return true;
            return false;
        }
    }
}

DocsExchange/Controllers/FilterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BusinessLogic.Interfaces;
using WebStore.Models.Filters;
using DataAccess.Context;
using DataAccess;
using WebStore.ViewModels;
using Domain.Models;
using AutoMapper;
using Newtonsoft.Json;

namespace WebStore.Controllers
{
    public class FilterController : Controller
    {
        private readonly IProductBusinessLogic _productBusinessLogic;
        private readonly IMapper _mapper;
        private readonly WebStoreDbContext _context;
        public FilterController(WebStoreDbContext context, IProductBusinessLogic productBusinessLogic, IMapper mapper)
        {
            _context = context;
            _productBusinessLogic = productBusinessLogic;
            _mapper = mapper;
        }

        [HttpGet]
        public string GetFilters()
        {
            var _colorRep = new ProductColorRepository(_context);
            var _metalRep = new ProductMetalRepository(_context);
            var _typeRep = new ProductTypeRepository(_context);
            var _statusRep = new ProductStatusRepository(_context);
            var _statusAvRep = new ProductAvStatusRepository(_context);
            var _genderRep = new GenderRepository(_context);


            var filters = new ProductsFilters()
            {
                ColorList = _colorRep.GetAllAvailable().Select(_mapper.Map<ProductColorView>),
                MetalList = _metalRep.GetAllAvailable(),
                GenderList = _genderRep.GetAllAvailable(),
                TypeList = _typeRep.GetAllAvailable(),
                StatusList = _statusRep.GetAllAvailable(),
                StatusAvList = _statusAvRep.GetAllAvailable()
            };

            ViewBag.Data = JsonConvert.SerializeObject(filters);
            return ViewBag.Data;
        }

        [HttpPost]
        public string Filter([FromBody] string filters)
        {
            List<FiltersView> filtersView = JsonConvert.DeserializeObject<List<FiltersView>>(filters);
            IEnumerable<ProductColorView> colorFilter = GetColorFilters(filtersView).Select(_mapper.Map<ProductColorView>);

            var products = _productBusinessLogic
                .GetAll()
                .Where(@prod =>
                    FilterByColor(@prod, colorFilter))
                .ToList();
            List<ProductView> models = new List<ProductView>();
            foreach (var item in products)
            {
                models.Add(_mapper.Map<ProductView>(item));
            }

            //ViewBag.Data = models.OrderBy(x => x.Name).ToList();
            //ViewBag.Filters = new ProductsFilters() { };
            //return RedirectToAction("Index", "Catalog");
            //string prodList = JsonConvert.SerializeObject(ViewBag.Data);
            ViewBag.Data = JsonConvert.SerializeObject(models.OrderBy(x => x.Name).ToList());
            return ViewBag.Data;
        }
        private bool FilterByProductName(Product @item, string prodFilter)
        {
            if (String.IsNullOrEmpty(prodFilter))
                return true;
            if (@item.Name == null)
                return false;
            var prod = _productBusinessLogic.GetByStr(@item.Name).FirstOrDefault();
            if (prod != null && prod.Name.Contains(prodFilter))
                return true;
            return false;
        }
        public IEnumerable<ProductColor> GetColorFilters(List<FiltersView> filtersView)
        {
            var _colorRep = new ProductColorRepository(_context);
            List<ProductColor> colorFilter = new List<ProductColor> { };
            foreach (FiltersView item in filtersView)
            {
                if (item.Checked)
                {
                    string[] result = item.Id.Split(new char[] { '_' }, StringSplitOptions.None);

                    if ((result[1] != null) && (result[0] == "color"))
                    {
                        colorFilter.Add(_colorRep.GetById(Int32.Parse(result[1])));
                    }
                }
            }
            return colorFilter.ToList();
        }
        private bool FilterByColor(Product @item, IEnumerable<ProductColorView> filter)
        {
            if (!filter.Any()) { return true; }
            foreach (ProductColorView color in filter)
            {
                if (@item != null && item.ProductColor == color.Id)
                    return true;
            }
            return false;
        }
        private bool FilterByMetalName(Product @event, IEnumerable<int> filter)
        {
            throw new System.NotImplementedException();
        }
        private bool FilterByTypeName(Product @event, IEnumerable<int> filter)
        {
            throw new System.NotImplementedException();
        }
        private bool FilterByStatusName(Product @event, IEnumerable<int> filter)
        {
            throw new System.NotImplementedException();
        }
        private bool FilterByStatusAvName(Product @event, IEnumerable<int> filter)
        {
            throw new System.NotImplementedException();
        }
        private bool FilterByGenderName(Product @event, IEnumerable<int> filter)
        {
            throw new System.NotImplementedException();
        }
        //var colorFilter = filtersItems.ColorList;
        //var metalFilter = filtersItems.MetalList;
        //var typeFilter = filtersItems.TypeList;
        //var statusFilter = filtersItems.StatusList;
        //var statusAvFilter = filtersItems.StatusAvList;
        //var genderFilter = filtersItems.GenderList;

        //var products = _productBusinessLogic
        //    .GetAll()
        //    .Where(@prod =>
        //        FilterByColorName(@prod, colorFilter)
        //        ).ToList();
        //List<ProductView> models = new List<ProductView>();
        //foreach (var item in products)
        //{
        //    models.Add(_mapper.Map<ProductView>(item));
        //}
        //ViewBag.Data = models.OrderBy(x => x.Name).ToList();
    }
}

DocsExchange/Views/Catalog/Index.cshtml
@using WebStore.Models.Filters
@using WebStore.ViewModels
@using Domain.Models
@model WebStore.Models.Filters.ProductsFilters
@using Newtonsoft.Json;

@{
    ViewData["Title"] = "Каталог товарів";
}

@{
    //List<ProductView> prodList = ViewBag.Data;
    //string prodList = JsonConvert.SerializeObject(ViewBag.Data);
    string prodList = ViewBag.Data;
    ProductsFilters filters = ViewBag.Filters;
}

<link href="~/css/catalog.css" rel="stylesheet">

@section Scripts {

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript">

        //$(".filterJS").change(function setStatus() {
        function Check() {
            var filtersArr = [];
            var elements = document.getElementsByClassName('filter');
            for (let item of elements) {
                filtersArr.push({ Id: item.id, Checked: item.checked });
            }
            var filters = JSON.stringify(filtersArr);
            $.ajax({
                url: '/Filter/Filter',
                type: "POST",
                data: JSON.stringify(filters),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    loadGoods(data);
                },
                error: function (response) {
                    console.log(response.responseText);
                },
                failure: function (response) {
                    console.log(response.responseText);
                }
            })
        };
        //});
        $(document).ready(function () {
            loadFilters();
            loadGoods();
        });
        function loadFilters(){
            $.ajax({
                url: '@Url.Action("GetFilters", "Filter")',
                type: "GET",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (filters) {
                    rawFilters(filters);
                }
            });
        }
        function clearElem(elementID)
        {
            document.getElementById(elementID).innerHTML = "";
        }
        function rawFilters(filters) {
            var ColorList = filters.ColorList;
            var MetalList = filters.MetalList;
            var GenderList = filters.GenderList;
            var TypeList = filters.TypeList;
            var StatusList = filters.StatusList;
            var StatusAvList = filters.StatusAvList;

            var tb = document.getElementById('table-filters');
            var field = document.createElement('fieldset');
            tb.appendChild(field);
            var div = document.createElement('div');
            div.setAttribute("id", "checkboxes");

            addUl(div, field, MetalList, "metal_", "Тип металу:");
            addUl(div, field, ColorList, "color_", "Колір:");
            addUl(div, field, GenderList, "gender_", "Стать:");
            addUl(div, field, TypeList, "type_", "Тип виробу:");
            addUl(div, field, StatusList, "status_", "Новинки:");
            addUl(div,field,StatusAvList,"statusav_","Наявніст:");
        }
        function rawGoods(data) {
            clearElem("productTable");
            var tbody = document.getElementById('productTable');
            
            data.forEach(element => {
                var tr = document.createElement("tr");
                tbody.appendChild(tr);
                
                console.log(element);
                var td = document.createElement('td');
                td.setAttribute("class","col-lg-2");
                tr.appendChild(td);
                td.innerHTML = element.Name;
                
            });
        };
        function addUl(div,field, list, pref, leb) {
            var ul = document.createElement('ul');
            var label = document.createElement('label');
            field.appendChild(div);
            label.innerHTML = leb;
            div.appendChild(label);
            ul.setAttribute("class", "ulCheckboxes");
            div.appendChild(ul);
            list.forEach(element => {
                var li = document.createElement('li');
                ul.appendChild(li);
                var inp = document.createElement("INPUT");
                inp.setAttribute("type", "checkbox");
                inp.setAttribute("class", "filter");
                inp.setAttribute("id", pref + element.Id);
                inp.setAttribute("onclick", "Check()");
                li.appendChild(inp);
                li.append(element.Name);
            });
        }
        function loadGoods(data = null) {
            if (data == null) {
                $.ajax({
                    url: '@Url.Action("getGoods", "Catalog")',
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (data) {
                        rawGoods(data);
                    }
                });
            } else {
                rawGoods(data);
            }
        }
    </script>
}
<h2>Каталог товарів</h2>

<table class="table col-lg-10">
    <thead>
        <tr>
            <th class="col-lg-1">Фільтри</th>
            <th class="col-lg-2">Назва</th>
            <th class="col-lg-1">Тип товару</th>
            <th class="col-lg-1">Тип металу</th>
            <th class="col-lg-1">Колір</th>
            <th class="col-lg-1">Стать</th>
            <th class="col-lg-1">Вага</th>
            <th class="col-lg-1">Кількість</th>
            <th class="col-lg-1">Ціна</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="col-lg-1" id="table-filters">
                @*@using (Html.BeginForm("CatalogFilter", "Filter", FormMethod.Post))
                {
                    <fieldset>
                        <form asp-action="CatalogFilter">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div id="checkboxes">
                                <label>Тип металу:</label>
                                <ul>
                                    @foreach (ProductMetal item in filters.MetalList)
                                    {
                                        <li><input type="checkbox" class="filter" id="metal_@Html.DisplayFor(modelItem => item.Id)"> @Html.DisplayFor(modelItem => item.Name)</li>
                                    }
                                </ul>
                                <label>Колір:</label>
                                <ul>
                                    @foreach (ProductColorView item in filters.ColorList)
                                    {
                                        <li><input type="checkbox" class="filter" id="color_@Html.DisplayFor(modelItem => item.Id)"> @Html.DisplayFor(modelItem => item.Name)</li>
                                    }
                                </ul>
                                <label>Стать:</label>
                                <ul>
                                    @foreach (Gender item in filters.GenderList)
                                    {
                                        <li><input type="checkbox" class="filter" id="gender_@Html.DisplayFor(modelItem => item.Id)"> @Html.DisplayFor(modelItem => item.Name)</li>
                                    }
                                </ul>
                                <label>Тип виробу:</label>
                                <ul>
                                    @foreach (ProductType item in filters.TypeList)
                                    {
                                        <li><input type="checkbox" class="filter" id="type_@Html.DisplayFor(modelItem => item.Id)"> @Html.DisplayFor(modelItem => item.Name)</li>
                                    }
                                </ul>
                                <label>Новинки:</label>
                                <ul>
                                    @foreach (ProductStatus item in filters.StatusList)
                                    {
                                        <li><input type="checkbox" class="filter" id="status_@Html.DisplayFor(modelItem => item.Id)"> @Html.DisplayFor(modelItem => item.Name)</li>
                                    }
                                </ul>
                                <label>Наявніст:</label>
                                <ul>
                                    @foreach (ProductAvailabilityStatus item in filters.StatusAvList)
                                    {
                                        <li><input type="checkbox" class="filter" id="statusav_@Html.DisplayFor(modelItem => item.Id)"> @Html.DisplayFor(modelItem => item.Name)</li>
                                    }
                                </ul>
                            </div>
                        </form>
                    </fieldset>
                }*@
            </td>
            <td class="col-lg-2" >
                <table class="table col-lg-9">
                    <thead>
                        <tr>
                            @*<th class="col-lg-2">Назва</th>
                            <th class="col-lg-1">Тип товару</th>
                            <th class="col-lg-1">Тип металу</th>
                            <th class="col-lg-1">Колір</th>
                            <th class="col-lg-1">Стать</th>
                            <th class="col-lg-1">Вага</th>
                            <th class="col-lg-1">Кількість</th>
                            <th class="col-lg-1">Ціна</th>*@
                        </tr>
                    </thead>
                    <tbody id="productTable">
                        @*@foreach (ProductView item in prodList)
                            {
                                <tr>
                                    <td class="col-lg-2">@Html.DisplayFor(modelItem => item.Name)</td>
                                    <td class="col-lg-1">@Html.DisplayFor(modelItem => item.ProductTypeName)</td>
                                    <td class="col-lg-1">@Html.DisplayFor(modelItem => item.ProductMetalName)</td>
                                    <td class="col-lg-1">@Html.DisplayFor(modelItem => item.ProductColorName)</td>
                                    <td class="col-lg-1">@Html.DisplayFor(modelItem => item.GenderName)</td>
                                    <td class="col-lg-1">@Html.DisplayFor(modelItem => item.Weight)</td>
                                    <td class="col-lg-1">@Html.DisplayFor(modelItem => item.Amount)</td>
                                    <td class="col-lg-1">@Html.DisplayFor(modelItem => item.Price)</td>
                                </tr>
                            }*@
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>